# Generated by Django 4.0.2 on 2023-03-23 06:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='age',
            field=models.CharField(default=datetime.datetime(2023, 3, 23, 6, 26, 5, 839298, tzinfo=utc), max_length=3),
            preserve_default=False,
        ),
    ]
