# Generated by Django 4.0.2 on 2023-03-23 07:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_candidate_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='phone',
            field=models.CharField(default=datetime.datetime(2023, 3, 23, 7, 3, 24, 311858, tzinfo=utc), max_length=13),
            preserve_default=False,
        ),
    ]
