# Generated by Django 4.0.2 on 2023-03-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_candidate_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='Situation',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Dispproved', 'Dispproved')], default='Pending', max_length=50, null=True),
        ),
    ]
